theme: jekyll-theme-minimal
title: 'Introduction to R for Bioinformatics'
show_downloads: True
google_analytics: True
navigation:
  - title: Home
    url: /

  - heading: Introduction
  - title: Introduction to the Workshop and the Core
    url: base/welcome
  - title: Schedule
    url: base/schedule

  - heading: Support
  - title: Slack
    url: base/slack
  - title: Zoom
    url: base/zoom
  - title: Cheat Sheets
    url: base/cheatSheetIndex

  - heading: Introduction to R
  - title: Introduction to R Day 1
    url: R/Intro2R_day1
  - title: Introduction to R Day 2
    url: R/Intro2R_day2
  - title: Introduction to R Day 3
    url: R/Intro2R_day3

  - heading: ETC
  - title: Closing thoughts
    url: base/closing
  - title: Github page
    url: https://github.com/ucdavis-bioinformatics-training/2021-June-Introduction-to-R-for-Bioinformatics
  - title: Biocore website
    url: http://bioinformatics.ucdavis.edu
